/* eslint-disable no-console */
import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';


// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: [
        'https://www.googleapis.com/auth/spreadsheets',
    ],
});

const AccessSheet = async(): Promise<void> => {
    const doc = new GoogleSpreadsheet('https://docs.google.com/spreadsheets/d/1FBq9HC0oHSxE2TVoM-WkVQYo9LZkBNo0dy3ssa_bXBs/edit#gid=0', serviceAccountAuth);

    await doc.loadInfo(); // loads document properties and worksheets
    console.log(doc.title);
    await doc.updateProperties({ title: 'renamed doc' });

    const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
    console.log(sheet.title);
    console.log(sheet.rowCount);
};

export default AccessSheet;

